#!/usr/bin/env bash
# transfer to a server

if [ "$#" -lt 3 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
    exit;
fi;
file_path="$1"
ip_address="$2"
user_name="$3"
ssh_path="$4"
if [ "$#" -lt 4 ]
then
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
    scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi;
