#!/usr/bin/env bash
# install nginx on remote server
# allows incoming HTTP traffic through the firewall using ufw
# configure Nginx to serve a custom page /var/www/html/index.html
# Using the service nginx restart command
# Not accepting connections on port 8080, TCP traffic is not allowed on port 8080
# Not running on port 80, Nginx is not listening on port 80
# Not running as nginx user, Nginx is not running as nginx user

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
