#!/usr/bin/env bash
# install nginx on remote server
# allows incoming HTTP traffic through the firewall using ufw
# configure Nginx to serve a custom page /var/www/html/index.html
# Not running as nginx user, Nginx is not running as nginx user

sudo apt-get update
sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
service nginx start
