#!/usr/bin/env bash
# this Script configures Nginx server with a custom header
sudo apt-get -y update
if ! [ -x "$(command -v nginx)" ]; then
  sudo apt-get -y install nginx
fi
echo "Ceci n'est pas une page" | sudo tee /var/www/error/404.html > /dev/null
custom_config="add_header X-Served-By \$hostname;"
sudo sed -i "/server_name _/a $custom_config" /etc/nginx/sites-available/default
if sudo systemctl is-active --quiet nginx; then
    sudo systemctl restart nginx
else
    sudo systemctl start nginx
fi
