#!/usr/bin/env bash
# script that pings IP 5 Times Passed as argument
#String in our argument

IP="${1}"
fn=$(basename "${BASH_SOURCE[@]}")

if ! [ "$IP" ]; then
echo "Usage: ${fn} {IP_ADDRESS}"
else
ping -c 5 "${IP}"
fi
