#!/usr/bin/env bash
# Configures (ufw) firewall to block all incoming traffic
# except for TCP ports ssh=22,(https ssl=443 and  http =80)

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
