#!/usr/bin/env bash
# Run Apache on the Docker container holbertonschool/265-0.
echo "ServerName localhost" | sudo tee -a /etc/apache2/conf-available/docker.conf
sudo a2enconf docker
sudo service apache2 start
